CREATE TABLE users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	age INT NOT NULL CHECK (age BETWEEN 13 AND 120),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);